name: Main

on:
  push:
    branches:
      - main


concurrency:
  group: ${{ github.workflow }} 

jobs:
  apply:
    permissions:
      id-token: write
      contents: write
    uses: fivexl/gh-workflow-tf-plan-apply/.github/workflows/base.yml@v0.0.26
    strategy:
      fail-fast: false
      matrix:
        environment: [beta, prod]
        include:
          - aws_role_arn: arn:aws:iam::244531986313:role/gh_actions_reporter
            environment: beta
          - aws_role_arn: arn:aws:iam::274425519734:role/gh_actions_reporter
            environment: prod
    with:
      aws_region: eu-central-1
      aws_role_arn: ${{ matrix.aws_role_arn }}
      aws_default_region: eu-central-1
      working_directory: deployment/terraform/
      tf_apply: 'true'
      tf_version: v1.9.1
      tf_additional_env_vars: '{"TF_VAR_KOSLI_HOST": "${{ vars.TF_VAR_KOSLI_HOST }}"}'
